// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Prefer local overrides from .env.local, then fall back to .env.
loadEnv({ path: ".env.local" });
loadEnv();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx src/seed.ts",
  },
  datasource: {
    url:
      process.env["POSTGRES_PRISMA_URL"] ??
      process.env["PRISMA_DATABASE_URL"] ??
      process.env["DATABASE_URL"],
  },
});
